// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJKgoT51hXiiZGt-jkd-9Apn4AhO_HUdA',
    appId: '1:510987550271:web:69cdc47cb7aeb9bc22028a',
    messagingSenderId: '510987550271',
    projectId: 'fir-flutter-codelab-b87a2',
    authDomain: 'fir-flutter-codelab-b87a2.firebaseapp.com',
    databaseURL: 'https://fir-flutter-codelab-b87a2-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-b87a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNmnR1y2pEPkUCd0cWGXLP3tznOvqaHDY',
    appId: '1:510987550271:android:c468f49b5d00f00f22028a',
    messagingSenderId: '510987550271',
    projectId: 'fir-flutter-codelab-b87a2',
    databaseURL: 'https://fir-flutter-codelab-b87a2-default-rtdb.firebaseio.com',
    storageBucket: 'fir-flutter-codelab-b87a2.appspot.com',
  );
}
